### ISSUE TITLE
Convert the code to vue 2 ?

### ISSUE THREAD

**Issue by mkantautas** [OneWayTech/vue-daterangepicker-component#1]
Hello, could you add some usage examples of using this in vue.js 2 ?

**Comment by kenberkeley** [comment]
I suggest using ElementUI instead

**Comment by kenberkeley** [comment]
this repo is deprecated

**Comment by lfaveur** [comment]
@kenberkeley not a bad idea but we have less options with Element UI

**Comment by kenberkeley** [comment]
@lfaveur DIY
